import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight, Loader2 } from "lucide-react";
import { Fragment } from "react";
import { Button } from "../../../components/ui/button";
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from "../../../components/ui/table";
export function EmptyRow({ colSpan, children }) {
    return (_jsx("td", { colSpan: colSpan, className: "p-4 text-center text-muted-foreground", children: children }));
}
export function DataTable({ data, columns, isLoading = false, emptyMessage = "No data", onSort, currentSort, pagination }) {
    const totalPages = pagination ? Math.max(1, Math.ceil(pagination.total / pagination.pageSize)) : 1;
    return (_jsx("div", { className: "space-y-4", children: _jsx("div", { className: "overflow-x-auto rounded-md border", children: _jsxs(Table, { children: [_jsx(TableHeader, { children: _jsx(TableRow, { children: columns.map((column) => {
                                const isSorted = currentSort?.key === column.key;
                                const direction = isSorted ? currentSort?.direction : undefined;
                                return (_jsx(TableHead, { className: column.className ?? "", children: column.sortable && onSort ? (_jsxs("button", { type: "button", className: "flex items-center gap-1", onClick: () => onSort(column.key), children: [column.header, isSorted ? (_jsx("span", { children: direction === "asc" ? "▲" : "▼" })) : (_jsx("span", { className: "text-muted-foreground", children: "\u2195" }))] })) : (column.header) }, column.key));
                            }) }) }), _jsx(TableBody, { children: isLoading ? (_jsx(TableRow, { children: _jsx(TableCell, { colSpan: columns.length, className: "h-24 text-center", children: _jsx(Loader2, { className: "mx-auto h-5 w-5 animate-spin" }) }) })) : data.length === 0 ? (_jsx(TableRow, { children: _jsx(EmptyRow, { colSpan: columns.length, children: emptyMessage }) })) : (data.map((row, rowIndex) => (_jsx(Fragment, { children: _jsx(TableRow, { children: columns.map((column) => (_jsx(TableCell, { className: column.className ?? "", ...column.cellProps, children: column.render ? column.render(row) : column.accessor ? column.accessor(row) : row[column.key] }, column.key))) }) }, rowIndex)))) }), pagination && (_jsx(TableCaption, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: ["Page ", pagination.page, " of ", totalPages, " (", pagination.total, " items)"] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Button, { size: "sm", variant: "ghost", onClick: () => pagination.onPageChange(1), disabled: pagination.page <= 1, children: _jsx(ChevronsLeft, { className: "h-4 w-4" }) }), _jsx(Button, { size: "sm", variant: "ghost", onClick: () => pagination.onPageChange(Math.max(1, pagination.page - 1)), disabled: pagination.page <= 1, children: _jsx(ChevronLeft, { className: "h-4 w-4" }) }), _jsx(Button, { size: "sm", variant: "ghost", onClick: () => pagination.onPageChange(Math.min(totalPages, pagination.page + 1)), disabled: pagination.page >= totalPages, children: _jsx(ChevronRight, { className: "h-4 w-4" }) }), _jsx(Button, { size: "sm", variant: "ghost", onClick: () => pagination.onPageChange(totalPages), disabled: pagination.page >= totalPages, children: _jsx(ChevronsRight, { className: "h-4 w-4" }) })] })] }) }))] }) }) }));
}
